services:
  postgres:
    env_file:
      - .env
    build:
      context: internal/carline/infrastructure/etc/postgres
    container_name: postgres
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - carline

  rabbitmq:
    env_file:
      - .env
    build:
      context: internal/carline/infrastructure/etc/rabbitmq
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./internal/carline/infrastructure/etc/rabbitmq:/etc/rabbitmq
    networks:
      - carline

  go:
    env_file:
      - .env
    build:
      context: .
    container_name: go
    ports:
      - "9991:9990"
    volumes:
      - .:/usr/src/app:rw
    networks:
      - carline

networks:
  carline:
    name: carline

volumes:
  dbdata:
    driver: local
