services:
  eventstore:
    env_file:
      - .env
    build:
      context: internal/carline/infrastructure/etc/eventstore
    container_name: eventstore
    ports:
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    networks:
      - carline

  rabbitmq:
    env_file:
      - .env
    build:
      context: internal/carline/infrastructure/etc/rabbitmq
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./internal/carline/infrastructure/etc/rabbitmq:/etc/rabbitmq
    networks:
      - carline

  go:
    env_file:
      - .env
    build:
      context: .
    container_name: go
    ports:
      - "9990:9990"
    volumes:
      - .:/usr/src/app:rw
    networks:
      - carline

networks:
  carline:
    name: carline

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
