export enum DomainEvents {
  ALL = 'ALL',
  SCHOOL_ADDED = 'SCHOOL_ADDED',
  SCHOOL_REMOVED = 'SCHOOL_REMOVED',
  STUDENTS_IMPORTED = 'STUDENTS_IMPORTED',
  STUDENT_REMOVED = 'STUDENT_REMOVED',
  STUDENT_DISMISSED = 'STUDENT_DISMISSED',
  USER_ADDED = 'USER_ADDED',
  USER_REMOVED = 'USER_REMOVED'
}
