// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	mail2 "github.com/pascalallen/carline/internal/carline/domain/mail"
	"github.com/pascalallen/carline/internal/carline/domain/security_token"
	"github.com/pascalallen/carline/internal/carline/infrastructure/database"
	"github.com/pascalallen/carline/internal/carline/infrastructure/mail"
	"github.com/pascalallen/carline/internal/carline/infrastructure/messaging"
	"github.com/pascalallen/carline/internal/carline/infrastructure/repository"
	"github.com/sendgrid/sendgrid-go"
	"os"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func InitializeContainer() Container {
	db := database.NewPostgresSession()
	permissionRepository := repository.NewPostgresPermissionRepository(db)
	roleRepository := repository.NewPostgresRoleRepository(db)
	userRepository := repository.NewPostgresUserRepository(db)
	security_tokenRepository := repository.NewPostgresSecurityTokenRepository(db)
	schoolRepository := repository.NewPostgresSchoolRepository(db)
	studentRepository := repository.NewPostgresStudentRepository(db)
	connection := messaging.NewRabbitMQConnection()
	commandBus := messaging.NewRabbitMqCommandBus(connection)
	queryBus := messaging.NewSynchronousQueryBus()
	eventDispatcher := messaging.NewRabbitMqEventDispatcher(connection)
	client := mail.NewSendGridMailClient()
	service := ProvideMailService(client)
	security_tokenService := security_token.NewService(security_tokenRepository)
	container := NewContainer(db, permissionRepository, roleRepository, userRepository, security_tokenRepository, schoolRepository, studentRepository, connection, commandBus, queryBus, eventDispatcher, client, service, security_tokenService)
	return container
}

// wire.go:

func ProvideMailService(sendGridClient *sendgrid.Client) mail2.Service {
	env := os.Getenv("APP_ENV")
	if env == "production" {
		return mail.NewSendGridMailService(sendGridClient)
	}

	host := os.Getenv("MAILGUN_HOST")
	port := os.Getenv("MAILGUN_PORT")
	username := os.Getenv("MAILGUN_USERNAME")
	password := os.Getenv("MAILGUN_PASSWORD")

	return mail.NewMailgunMailService(host, port, username, password)
}
